version: '3.8'
services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # 現在のディレクトリをコンテナの /app にマウント
      - /app/node_modules # node_modules をボリュームとして除外 (ホストの node_modules を使用)